package exceptionhandling;

public class ExceptionDemo2 {

	public static void main(String[] args) {

		int intArray1[] = {10,20,30};
		
		System.out.println(intArray1[4]);
		System.out.println("Program ended");
	}

}
